spec:
    proxy:
        port: 8085
        protocol: TCP
        transport:
            lifeCycle:
                requestAcceptGraceTimeout: 1s
                graceTimeOut: 5s
            respondingTimeouts:
                idleTimeout: 3m0s
        forwardedHeaders:
            insecure: true
transport:
    serverName: default
    maxIdleConnPerHost: 100
middleware:
    replaceHost:
        scheme: http
        host: 127.0.0.1:8150
